---
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
docker_swarm_interface: eth0
docker_swarm_managers_ansible_group: docker-swarm-managers
docker_swarm_port: "2377"
docker_swarm_primary_manager: "{{ groups[docker_swarm_managers_ansible_group][0] }}"
docker_swarm_workers_ansible_group: docker-swarm-workers
