language: python
python:
- '3.8'
before_install:
- openssl aes-256-cbc -K $encrypted_cd927ea5e858_key -iv $encrypted_cd927ea5e858_iv
  -in service-account-key.json.enc -out service-account-key.json -d
#- curl https://sdk.cloud.google.com | bash > /dev/null
#- source "$HOME/google-cloud-sdk/path.bash.inc"
#- gcloud auth activate-service-account --key-file=service-account-key.json
#- gcloud config set project "${GCP_PROJECT_ID}"
install:
- pip install -r tests/requirements.txt
- ansible-galaxy collection install -r requirements.yml
- ansible-galaxy role install -r requirements.yml
script:
- ansible-lint --version
- ansible-lint -p roles/* playbook.yml playbook-public.yml
- cd roles/install_docker
- molecule test
env:
  global:
  - SA="${TRAVIS_BUILD_DIR}/service-account-key.json"
  - GCP_PROJECT_ID=smarket-237213
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
