language: python
python:
- "3.8"

install:
- pip install -r tests/requirements.txt
- ansible-galaxy collection install community.general

script:
- ansible-lint --version
- ansible-lint -p roles/* playbook.yml playbook-public.yml
