language: python
python:
- '3.8'

#before_install:
#- openssl aes-256-cbc -K $encrypted_cd927ea5e858_key -iv $encrypted_cd927ea5e858_iv
#  -in service-account-key.json.enc -out service-account-key.json -d
#install:
#- pip install -r tests/requirements.txt
#- ansible-galaxy collection install -r requirements.yml
#- ansible-galaxy role install -r requirements.yml

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: "Code linting"
      install:
        - pip install -r tests/requirements-lint.txt
      script:
        - ansible-lint -p roles/* playbook.yml playbook-public.yml

    - stage: test
      name: "Test install_docker role"
      before_install:
        - openssl aes-256-cbc -K $encrypted_cd927ea5e858_key -iv $encrypted_cd927ea5e858_iv
          -in service-account-key.json.enc -out service-account-key.json -d
      install:
        - pip install -r tests/requirements-test.txt
        - ansible-galaxy collection install -r requirements.yml
        - ansible-galaxy role install -r requirements.yml
      before_script:
        - cd roles/install_docker
      script:
        - molecule test
env:
  global:
  - SA="${TRAVIS_BUILD_DIR}/service-account-key.json"
  - GCP_PROJECT_ID=smarket-237213
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
