- name: Provision Docker
  hosts: localhost
  vars:
    gcp_project: tim-inf-col-ap00017859p65-l0
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ~/service-account-key.json
    zone: "europe-west4-a"
    region: "europe-west4"
    instances:
    - centos-1
    - centos-2

  tasks:

    - name: Provision CentOS instances
      include_role:
        name: create-gcp-centos-instances
      with_items:
        - "{{ instances }}"
      loop_control:
        loop_var: instance_name

