- name: Provision Docker
  hosts: localhost
  vars:
    gcp_project: tim-inf-col-ap00017859p65-l0
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ~/service-account-key.json
    zone: "europe-west4-a"
    region: "europe-west4"
    instances:
    - centos-1
    - centos-2
    public_key: "{{ lookup('file', '/home/g11622966/provision-docker/ansible_rsa.pub') }}"

  tasks:

    - name: Provision CentOS instances
      include_role:
        name: instance
      with_items:
      - "{{ instances }}"
      loop_control:
        loop_var: instance_name

- name: Configure instances
  hosts: centos_instances
  connection: ssh
  become: True
  roles: 
    - vm-config
