- name: Provision environment
  hosts: localhost
  gather_facts: False
  vars:
    gcp_project: tim-inf-col-ap00017859p65-l0
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ~/service-account-key.json
    zone: "europe-west4-a"
    region: "europe-west4"
    instances:
    - centos-1
    - centos-2

  tasks:

    - name: Provision CentOS instances
      include_role:
        name: create-gcp-centos-instances
      with_items:
        - "{{ instances }}"
      loop_control:
        loop_var: instance_name

- name: Configure instances
  hosts: centos_instances
  become: True
  roles:
    - role: configure-instances
    - role: install-docker
      docker_daemon_options: {}
    - configure-docker

- name: Get client certificates
  hosts: centos_instances
  become: true
  vars:
    client_cert_dest_folder: "/home/{{ lookup( 'env', 'USER') }}/.docker"

  tasks:

    - name: Fetch client certificates
      fetch:
        src: "/root/.docker/{{ item }}"
        dest: "{{ client_cert_dest_folder }}"
      with_items:
        - "ca.pem"
        - "cert.pem"
        - "key.pem"

- name: Add to inventory
  hosts: localhost
  tasks:

    - name: Add host to swarm manager group
      add_host:
        name: "{{ hostvars[groups['centos_instances'][0]].ansible_hostname }}"
        groups:
          - docker-swarm-managers
        ansible_user: "{{ hostvars[groups['centos_instances'][0]].ansible_user }}"
        ansible_pipelining: false
        ansible_host: "{{ hostvars[groups['centos_instances'][0]].ansible_host }}"

    - name: Add host to swarm worker group
      add_host:
        name: "{{ hostvars[groups['centos_instances'][1]].ansible_hostname }}"
        groups:
          - docker-swarm-workers
        ansible_user: "{{ hostvars[groups['centos_instances'][1]].ansible_user }}"
        ansible_pipelining: false
        ansible_host: "{{ hostvars[groups['centos_instances'][1]].ansible_host }}"

- name: Configure Docker Swarm
  hosts: centos_instances
  become: True
  roles:
    - configure-docker-swarm




