- name: Provision Docker
  hosts: localhost
  vars:
    gcp_project: smarket-237213
    gcp_cred_kind: serviceaccount
    gcp_cred_file: /mnt/g/My Drive/ansible-env/ansible-vm/service-account-key-smarket.json
    zone: "europe-west4-a"
    region: "europe-west4"
    instances:
    - centos-1
    - centos-2
  #environment:
   # HTTP_PROXY: lelapomi.telecomitalia.local:8080
    #HTTPS_PROXY: lelapomi.telecomitalia.local:8080

  tasks:
    # - name: Provision VPC network
    #   gcp_compute_network:
    #     name: centos-network
    #     auto_create_subnetworks: yes
    #     project: "{{ gcp_project }}"
    #     auth_kind: "{{ gcp_cred_kind }}"
    #     service_account_file: "{{ gcp_cred_file }}"
    #     state: present
    #   register: network

    - name: Allow SSH connection
      gcp_compute_firewall:
        name: allow-ssh
        #network:
          #selfLink: "{{ network.id }}" #global/networks/centos-network
        allowed:
          - ip_protocol: tcp
            ports:
              - "22"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present


    - name: Provision CentOS instances
      include_role:
        name: instance
      with_items:
      - "{{ instances }}"
      loop_control:
        loop_var: instance_name

- name: Manage instances
  hosts: centos_instances
  connection: ssh
  become: True
  tasks:
    - name: Create directory
      command: mkdir pippo
      
