---
collections:
  - name: community.general
    version: "4.8.1"
  - name: ansible.posix
    version: "1.3.0"
  - name: google.cloud
    version: "1.0.2"
  - name: community.crypto
    version: "2.3.1"

roles:
  - name: geerlingguy.docker
    version: "4.2.2"
  - name: alexinthesky.secure-docker-daemon
    version: "v0.2"
