#- name: Print ansible_hostname
#  hosts: all
#  tasks:
#
#    - debug:
#        msg: "{{ ansible_hostname }}"

- name: Configure instances
  hosts: all
  become: True
  roles:
    - configure-docker

- name:
  hosts: all
  become: true
  vars:
    client_cert_dest_folder: "/home/{{ lookup( 'env', 'USER') }}/.docker"

  tasks:

    - name: Fetch client certificates
      fetch:
        src: "/root/.docker/{{ item }}"
        dest: "{{ client_cert_dest_folder }}"
      with_items:
        - "ca.pem"
        - "cert.pem"
        - "key.pem"

- name:
  hosts: localhost
  vars:
    client_key_folder: "/home/{{ lookup( 'env', 'USER') }}/.docker"


  tasks:

    - name: Test docker command
      command: "docker --tlsverify --tlscacert={{ client_key_folder }}/{{ item }}/root/.docker/ca.pem --tlscert={{ client_key_folder }}/{{ item }}/root/.docker/cert.pem --tlskey={{ client_key_folder }}/{{ item }}/root/.docker/key.pem -H={{ item }}:2376 version"
      with_items:
        - centos-1
        - centos-2
      register: output
#      environment:
#        DOCKER_HOST: "tcp://{{ ansible_host }}:2376"
#        DOCKER_TLS_VERIFY: 1

    - name: Docker version output
      debug:
        msg: "{{ output }}"
