- name: Configure instances
  hosts: all
  become: True
  roles:
    - configure-docker

- name:
  hosts: all
  become: true
  vars:
    client_cert_dest_folder: "/home/{{ lookup( 'env', 'USER') }}/.docker"
    
  tasks:

    - name: Fetch client certificates
      fetch:
        src: "/root/.docker/{{ item }}"
        dest: "{{ client_cert_dest_folder }}"
      with_items:
        - "ca.pem"
        - "cert.pem"
        - "key.pem"

    - name: Test docker command
      command: docker version
      register: output
      environment:
        DOCKER_HOST: "tcp://{{ ansible_host }}:2376"
        DOCKER_TLS_VERIFY: 1

    - name: Docker version output
      debug:
        msg: "{{ output }}"
