---
- name: Verify Docker version is 20.16
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Get docker version string
      shell: "docker -v"
      register: version

    - name: Extract docker version
      set_fact:
        docker_version: "{{ version.stdout.split()[2] }}"

    - name: Assert docker version is at least 20.10
      assert:
        that: docker_version is version('20.10', '>=')
