---
#- name: Read device information
#  community.general.parted: device=/dev/sda unit=GiB
#  register: sda_info

#- name: Read device information
#  community.general.parted: device=/dev/sdb unit=GiB
#  register: sdb_info

- name: Install lvm2 dependency
  package:
    name: lvm2
    state: present

- name: Create Docker Volume Group
  lvg:
    vg: docker-vg
    pvs: /dev/sdb
    pesize: 16

- name: Create Docker Logical Volume
  lvol:
      vg: docker-vg
      lv:  docker-lv
      size: 40g
      force: yes

- name: Create directory /var/lib/docker if does not exist
  file:
    path: /var/lib/docker
    state: directory
    mode: '0755'

- name: Format the xfs filesystem
  filesystem:
    fstype: xfs
    dev: /dev/docker-vg/docker-lv

- name: Mount the lv on /var/lib/docker
  mount:
    path: /var/lib/docker
    src: /dev/docker-vg/docker-lv
    fstype: xfs
    state: mounted
