---
- name: Install openssl
  package: 
    name: "openssl"
    state: present

- name: Generate certificates
  include_role:
    name: alexinthesky.secure-docker-daemon
  vars:
    dds_host: "{{ hostname }}"
  
- name: Set default TLS authentication
  copy:
    remote_src: yes
    src: "/root/.docker/"
    dest: "/home/{{ ansible_user }}/.docker/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0744'

- name: Ensure /etc/docker/ directory exists
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0

- name: Configure docker service
  copy:
    src: docker.service
    dest: /lib/systemd/system/docker.service
    mode: '0644'

- name: Reload daemon configuration
  systemd:
    daemon_reload: yes

- name: Configure Docker daemon options.
  copy:
    content: "{{ docker_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: '0644'
  when: docker_options.keys() | length > 0
  notify: restart docker

- name: Fetch client certificates
  fetch:
    src: "/root/.docker/{{ item }}"
    dest: "{{ client_cert_dest_folder }}"
    #flat: yes
  with_items:
    - "ca.pem"
    - "cert.pem"
    - "key.pem"
