- name: Allow SSH connection
  gcp_compute_firewall:
    name: allow-ssh
    allowed:
      - ip_protocol: tcp
        ports:
          - "22"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
