---
- name: Install Docker
  vars:
    docker_install_compose: "{{ compose }}"
    docker_edition: "{{ edition }}"
    docker_version: "{{ version }}"
    docker_users: "{{ users }}"
  include_role:
    name: geerlingguy.docker
