---
- name: Create {{ instance_name }} boot disk
  gcp_compute_disk:
    name: "{{ instance_name }}-boot"
    size_gb: 50
    type: pd-standard
    source_image: projects/centos-cloud/global/images/centos-7-v20220406
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: boot_disk

- name: Create {{ instance_name }} docker disk
  gcp_compute_disk:
    name: "{{ instance_name }}-docker"
    size_gb: 60
    type: pd-standard
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: docker_disk

  #- name: Create public IP address
  #gcp_compute_address:
  #  name: "{{ instance_name }}-address"
  #  region: "{{ region }}"
  #  project: "{{ gcp_project }}"
  #  auth_kind: "{{ gcp_cred_kind }}"
  #  service_account_file: "{{ gcp_cred_file }}"
  #  state: present
  #register: address

- name: Create {{ instance_name }} instance
  gcp_compute_instance:
    name: "{{ instance_name }}"
    machine_type: e2-micro
    disks:
    - auto_delete: 'true'
      boot: 'true'
      source: "{{ boot_disk }}"
    - auto_delete: 'true'
      boot: 'false'
      source: "{{ docker_disk }}"
    network_interfaces:
      - network: 
          selfLink: "global/networks/default"
      # access_configs:
      # - name: External NAT
      #   nat_ip: "{{ address }}"
      #   type: ONE_TO_ONE_NAT
    metadata:
      ssh-keys: "ansible:{{ public_key }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: instance

- name: Wait for SSH connection to come up
  import_tasks: "wait-for-connection.yml"

- name: Add host to centos_instances group
  import_tasks: "add-host-to-group.yml"
